.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH ndhcpd 8 "September 16, 2016" "" "NDHCPD"

.SH NAME
ndhcpd \- Very simple DHCP server implementation.

.SH SYNOPSIS
.B ndhcpd
.RI [ options ]
.br

.SH DESCRIPTION
\fBndhcpd\fP is tiny DHCP server with very basic functionality

.SH "SEE ALSO"

